eztsm/config/routes.rb
Rails.application.routes.draw do
  mount RailsSettingsUi::Engine, at: 'admin/settings'
  get 'home/index'

  root 'home#index'

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'sessions/new'
  post 'sessions' => 'sessions#create'

  get 'change_password' => 'password_resets#new'
  patch 'change_password' => 'password_resets#edit'

  get 'nodes' => 'nodes#index'
  post 'nodes' => 'nodes#create'
  get 'domains' => 'domains#index'
  get 'optsets' => 'optsets#index'
  get 'schedules' => 'schedules#index'
  patch 'schedules' => 'schedules#update'
  get 'active_schedules' => 'schedules#list_by_node'

  get 'node' => 'nodes#view'
  post 'node/rename' => 'nodes#rename'
  post 'node/update' => 'nodes#update'
  delete 'node' => 'nodes#delete'

  get 'reports/top50' => 'reports#get_top_50'
  get 'reports/orphaned_nodes' => 'reports#nodes_without_schedules'
  get 'reports/activity' => 'reports#last_7_days_activity'
  get 'reports/stgpools' => 'reports#stgpools_index'
  get 'reports/stgpool' => 'reports#show_stgpool'

  namespace :admin do
    get 'events' => 'events#index'
    get 'settings' => 'settings#index'
    resources 'users', :except => [ :show, :new ]
  end

end

eztsm/app/views/shared/_create_node_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="createNodeModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title">Create Node</h2>
      </div>
      <div class="modal-body">
        <div id="createNodeModalBodyErrors" class="text-danger"></div>
        <p>
          <% domains = []; opt_set = [] -%>
          <%= simple_form_for :node, :url => nodes_path, remote: true, :html => {:role => 'form'} do |f| %>
            <%= f.input :node_name, html: {autocomplete: 'off'} %>
            <%= f.input :password, html: {autocomplete: 'off'} %>
            <%= f.input :domain_name, :collection => domains, :label => "Domain", :include_blank => false %>
            <%= f.input :opt_set, :collection => opt_set, :label => "Option Set", :include_blank => false %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.button :submit, 'Create node', :class => 'btn btn-primary' %>
      </div>
          <% end -%>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

eztsm/app/views/shared/_error_messages.html.erb
<% unless @user.nil? -%>
  <% if @user.errors.any? -%>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <% if @user.new_record? -%>
        Unable to create user.
        <% else -%>
        Unable to update user <%= @user.login %>.
        <% end -%>
      </div>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end -%>
<% end -%>

eztsm/app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">ezTSM</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left" method="get" action=<%= nodes_path %> role="search">
        <div class="input-group">
          <input type="text" class="form-control" name="node_name" placeholder="Search node">
          <span class="input-group-btn">
            <button type="submit" class="btn btn-default">Submit</button>
          </span>
        </div>
      </form>
      <ul class="nav navbar-nav">
        <li><a href="#" onclick="callCreateNodeModal()">Create node</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="reportsDropDown" aria-haspopup="true" aria-expanded="true">Reports <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="reportsDropDownMenu">
            <li><%= link_to 'TOP 50 biggest filespaces', '/reports/top50' %></li>
            <li><%= link_to 'Nodes without schedules', '/reports/orphaned_nodes' %></li>
            <li><%= link_to 'Last 7 days activity', '/reports/activity' %></li>
            <li><%= link_to 'Storage pool status', '/reports/stgpools' %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless current_user.nil? -%>
          <%if current_user.is_admin -%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="adminDropDown" aria-haspopup="true" aria-expanded="true">Admin <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="adminDropDownMenu">
              <li><%= link_to 'Settings', admin_settings_path %></li>
              <li><%= link_to 'Manage users', admin_users_path, 'data-no-turbolink': true %></li>
              <li><%= link_to 'View Events', admin_events_path, 'data-no-turbolink': true %></li>
            </ul>
          </li>
          <%end -%>
        <%end -%>
        <%if current_user -%>
          <p class="navbar-text">Logged in as <%= current_user.login %></p>
          <li><%= link_to 'Change my password', change_password_path %></li>
          <li><%= link_to 'Log out', logout_path %></li>
        <%end -%>
      </ul>
    </div>
  </div>
</nav>