eztsm/config/routes.rb
Rails.application.routes.draw do
  mount RailsSettingsUi::Engine, at: 'admin/settings'
  get 'home/index'

  root 'home#index'

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'sessions/new'
  post 'sessions' => 'sessions#create'

  get 'change_password' => 'password_resets#new'
  patch 'change_password' => 'password_resets#edit'

  get 'nodes' => 'nodes#index'
  post 'nodes' => 'nodes#create'
  get 'domains' => 'domains#index'
  get 'optsets' => 'optsets#index'
  get 'schedules' => 'schedules#index'
  patch 'schedules' => 'schedules#update'
  get 'active_schedules' => 'schedules#list_by_node'

  get 'node' => 'nodes#view'
  post 'node/rename' => 'nodes#rename'
  post 'node/update' => 'nodes#update'
  delete 'node' => 'nodes#delete'

  get 'reports/top50' => 'reports#get_top_50'
  get 'reports/orphaned_nodes' => 'reports#nodes_without_schedules'
  get 'reports/activity' => 'reports#last_7_days_activity'
  get 'reports/stgpools' => 'reports#stgpools_index'
  get 'reports/stgpool' => 'reports#show_stgpool'

  namespace :admin do
    get 'events' => 'events#index'
    get 'settings' => 'settings#index'
    resources 'users', :except => [ :show, :new ]
  end

end

eztsm/app/controllers/nodes_controller.rb
class NodesController < ApplicationController

  def index
    if params[:node_name]
      @node_name = params[:node_name]
    else
      @node_name = ''
    end
    @filter = sanitize_for_tsm(@node_name).upcase
    @columns = [ 'node_name', 'tcp_address', 'domain_name', 'option_set', 'timestamp(lastacc_time, 0)']
    @select = tsmdb_select(@columns, 'nodes', "node_name like \'%#{@filter}%\'")
    @nodes = @select['output'].split(/\n/)
  end

  def view
    node_name = sanitize_for_tsm(params[:node_name])
    columns = ['NODE_NAME','DOMAIN_NAME','OPTION_SET','PLATFORM_NAME','TCP_NAME','TCP_ADDRESS','MAX_MP_ALLOWED','ARCHDELETE','BACKDELETE','LOCKED','LASTACC_TIME','LASTSESS_COMMMETH','LASTSESS_RECVD','LASTSESS_SENT','LASTSESS_DURATION','LASTSESS_IDLEWAIT','LASTSESS_COMMWAIT','LASTSESS_MEDIAWAIT','REG_ADMIN','REG_TIME']
    select = tsmdb_select(columns, 'nodes', "node_name = '#{node_name}'")
    
    result_csv = CSV.new(columns.join(',') + "\n" + select['output'], :headers => true, :header_converters => :symbol, :converters => :all)
    result_json = result_csv.to_a.map {|row| row.to_hash }

    respond_to do |format|
      format.json { render :json => result_json }
    end
  end

  def rename
    result = qtsm("rename node #{sanitize_for_tsm(params[:current_name])} #{sanitize_for_tsm(params[:new_name]).upcase}")
    respond_to do |format|
      format.json { render :json => result.to_json } 
    end
  end

  def update
    node_name = sanitize_for_tsm(params[:node_name])
    result = Hash.new
    result['output'] = 'No matching parameters' #Error message if no available parameters where given
 
    # Update password
    if params[:password]
      password = params[:password]
      
      # Check password length is more than 7 characters
      if password.length > 7
        # Accept only alphanumerical passwords
        if password =~ /\A[[:alnum:]]+\z/
          result = qtsm("update node #{node_name} #{password}")
        else
          result['exit_status'] = -1
          result['output'] = "Password should be alphanumeric only"
        end
      else
        result['exit_status'] = -1
        result['output'] = "Node's password should be at least 8 characters long."
      end
    end

    # Update domain
    if params[:domain]
      domain = sanitize_for_tsm(params[:domain])
      result = qtsm("update node #{node_name} domain=#{domain}")
    end

    # Update option set
    if params[:option_set]
      option_set = sanitize_for_tsm(params[:option_set])
      result = qtsm("update node #{node_name} cloptset=#{option_set}")
    end

    # Update max mp allowed
    if params[:max_mp_allowed]
      max_mp_allowed = sanitize_for_tsm(params[:max_mp_allowed])
      result = qtsm("update node #{node_name} maxnummp=#{max_mp_allowed}")
    end

    unless params[:backdelete].nil?
      if params[:backdelete] == 'true'
        result = qtsm("update node #{node_name} backdelete=yes")
      elsif params[:backdelete] == 'false'
        result = qtsm("update node #{node_name} backdelete=no")
      end
    end

    respond_to do |format|
      format.json { render :json => result.to_json }
    end
  end

  def delete
    if params[:node_name]
      result = qtsm("update node #{params[:node_name]} domain='RETIREDNODES'")
      if result['exit_status'] == 0
        flash[:success] = "Node successfully switched to 'RETIREDNODES' domain"
      else
        flash[:danger] = "Unable to delete node #{params[:node_name]}. Error details: #{result['output']}"
      end
    else
      flash[:danger] = "You must supply a node name to delete"
    end
    redirect_to nodes_url(node_name: params[:search])
  end

  def create
    unless params[:node][:node_name].nil? or params[:node][:password].nil? or params[:node][:domain_name].nil? or params[:node][:opt_set].nil?
      @node_name = sanitize_for_tsm(params[:node][:node_name])
      password = sanitize_for_tsm(params[:node][:password])
      domain_name = sanitize_for_tsm(params[:node][:domain_name])
      opt_set = sanitize_for_tsm(params[:node][:opt_set])
      
      if password.length < 8
        @result = Hash.new
        @result['exit_status'] = -1
        @error_message = "Node's password should be at least 8 characters long."
      else
        @result = qtsm("register node #{@node_name} #{password} domain=#{domain_name} cloptset=#{opt_set}")
    
        if @result['exit_status'] == 0
          flash[:success] = "Node #{@node_name} successfully created"
        else
          @error_message = "Unable to create node #{@node_name}. Error details: #{@result['output']}"
        end
      end
    end
    render 'nodes/create_node_modal_response' 
  end
end

eztsm/app/helpers/nodes_helper.rb
module NodesHelper
end

eztsm/app/views/nodes/create_node_modal_response.js.erb
<% if @result['exit_status'] == 0 -%>
  window.location.href='<%= nodes_path(node_name: @node_name) %>'
<% else -%>
  $("#createNodeModalBodyErrors").html("<%= escape_javascript(@error_message) %>")
<% end %>

eztsm/app/views/nodes/index.html.erb
<div class="jumbotron">
  <h1> Search Nodes</h1>
  <p>You searched for: '<%= @filter %>'</p>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="viewNodeModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3><span id="viewNodeModalHeader"></span></h3>
      </div>
      <div class="modal-body" style="overflow-y: auto">
        <div id="viewNodeModalBodyErrors"></div>
        <div id="viewNodeModalBodyMain"></div>
      </div>
      <div class="modal-footer" hidden="true">
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id='errors'>
  <h3>
    <% if @select['exit_status'] == 11 -%>
      <div class="text-danger text-center">Unable to find any node matching '<%=@filter %>'</div>
    <% elsif @select['exit_status'] != 0 -%>
      <div class="text-danger text-center">An error occured. Please try again later or contact your ezTSM administrator. Error code: <%= @select['exit_status'] %></div>
    <% end -%>
  </h4>
</div>

<button type="button" class="btn btn-primary has-tooltip" title="Create node" onclick="callCreateNodeModal()">Create Node</button><br />
<br />

<% if @select['exit_status'] == 0 -%>
<table class="table table-striped">
  <tr>
    <% @columns.each do |column| -%>
      <th><% case column 
             when 'node_name'%> Node
          <% when 'tcp_address' %> IP
          <% when 'domain_name' %> Domain
          <% when 'option_set' %> Client Option Set
          <% when 'timestamp(lastacc_time, 0)' %> Last Access
          <% end -%>
           </th>
    <% end -%>
    <th width='7%'></th>
  </tr>
 
  <% @nodes.each do |node| -%>
    <tr class="rowDblClick">
      <% node.split(',').each do |node_field| -%>
        <td><%= node_field %></td>
      <% end -%>
      <td><button type="button" class='btn btn-xs btn-primary has-tooltip' title='View or update node' onclick='getNodeNameFromTable(this)'><span class='glyphicon glyphicon-search'></span></button><%= link_to node_path(node_name: node.split(',').first, search: @filter), method: :delete, data: { confirm: "You'e about to delete the node #{node.split(',').first}. Are you sure?" }, class: 'btn btn-xs btn-danger has-tooltip', title:'Delete node', 'data-toggle' => 'tooltip' do %><span class='glyphicon glyphicon-trash'></span><% end %></td>  
    </tr>
  <% end -%>
</table>
<% end -%>