eztsm/config/routes.rb
Rails.application.routes.draw do
  mount RailsSettingsUi::Engine, at: 'admin/settings'
  get 'home/index'

  root 'home#index'

  get 'login' => 'sessions#new', :as => 'login'
  get 'logout' => 'sessions#destroy', :as => 'logout'
  get 'sessions/new'
  post 'sessions' => 'sessions#create'

  get 'change_password' => 'password_resets#new'
  patch 'change_password' => 'password_resets#edit'

  get 'nodes' => 'nodes#index'
  post 'nodes' => 'nodes#create'
  get 'domains' => 'domains#index'
  get 'optsets' => 'optsets#index'
  get 'schedules' => 'schedules#index'
  patch 'schedules' => 'schedules#update'
  get 'active_schedules' => 'schedules#list_by_node'

  get 'node' => 'nodes#view'
  post 'node/rename' => 'nodes#rename'
  post 'node/update' => 'nodes#update'
  delete 'node' => 'nodes#delete'

  get 'reports/top50' => 'reports#get_top_50'
  get 'reports/orphaned_nodes' => 'reports#nodes_without_schedules'
  get 'reports/activity' => 'reports#last_7_days_activity'
  get 'reports/stgpools' => 'reports#stgpools_index'
  get 'reports/stgpool' => 'reports#show_stgpool'

  namespace :admin do
    get 'events' => 'events#index'
    get 'settings' => 'settings#index'
    resources 'users', :except => [ :show, :new ]
  end

end

eztsm/app/models/user.rb
class User < ActiveRecord::Base

  has_many :events
  has_secure_password
    
  validates_presence_of :password_digest, :login
  validates :password, presence: { on: create }, length: { minimum: 8 }, if: :password_digest_changed?
  validates :login, :uniqueness => { :case_sensitive => false }
  validates :email, :allow_blank => true, :uniqueness => { :case_sensitive => false }
end

eztsm/app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  def index
    @users = User.order(:login)
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      respond_to do |format|
        format.js {
          log_event("Created user #{@user.login}")
          flash[:success] = "User #{@user.login} successfully created"
          render 'admin/users/user_modals_response'
        }
      end
    else
      respond_to do |format|
        format.js { render 'admin/users/user_modals_response' }
      end
    end
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    if @user.update_attributes(user_params)
      respond_to do |format|
        format.js { 
          log_event("Updated user #{@user.login}")
          flash[:success] = "User #{@user.login} successfully updated"
          render 'admin/users/user_modals_response'
        }
      end
    else
      respond_to do |format|
        format.js { render 'admin/users/user_modals_response' }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      log_event("Deleted user #{@user.login}")
      flash[:success] = "User deleted"
      redirect_to admin_users_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:login, :email, :description, :password, :is_admin)
  end
end

eztsm/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

eztsm/app/views/admin/users/_edit_user_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="user-<%= user.id %>-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <% if user.new_record? -%>
        <h2 class="modal-title">Create User</h2>
        <% else -%>
        <h2 class="modal-title">Edit User <%= user.login %></h2>
        <% end -%>
      </div>
      <div class="modal-body">
        <div id="errors-<%= user.id unless user.new_record?%>"></div>
        <p>
        <% if user.new_record? -%>
          <%= simple_form_for user, :url => admin_users_path(user), remote: true, :html => {:role => 'form'} do |f| %>
            <%= f.input :login %>
            <%= f.input :email %>
            <%= f.input :description %>
            <%= f.input :password -%>           
            <%= f.input :is_admin, label: 'Administrator', hint: 'Administrators inherit full rights, including managing users and permissions' %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.button :submit, 'Create user', :class => 'btn btn-primary' %>
      </div>
          <% end -%>
        <% else -%>
          <%= simple_form_for user, :url => admin_user_path(user), remote: true, :html => {:role => 'form'} do |f| %>
            <%= f.input :login %>
            <%= f.input :email %>
            <%= f.input :description %>
            <%= f.input :password, label: 'Change password' %>
            <%= f.input :is_admin, label: 'Administrator', hint: 'Administrators inherit full rights, including managing users and permissions' %>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.button :submit, 'Save changes', :class => 'btn btn-primary' %>
      </div>
          <% end -%>
        <% end -%>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

eztsm/app/views/admin/users/index.html.erb
<div class="jumbotron">
  <h1> Manage users</h1>
</div>

<%= render :partial => 'admin/users/edit_user_modal', :locals => { :user => @user }  %>

<%= link_to 'Create new user', '#', 'data-toggle' => 'modal', 'data-target' => '#user--modal', class: 'btn btn-primary' %><br />
<br />
  <% @users.each do |user| -%>
    <%= render :partial => 'admin/users/edit_user_modal', :locals => { :user => user }  %>
  <% end -%>
  <%= render 'shared/error_messages' %>
<table class="table table-striped">
  <tr>
    <th width="5%">Admin</th>
    <th width="19%">Login</th>
    <th width="20%">Email</th>
    <th width="50%">Description</th>
    <th width="6%"></th>
  </tr>
 
  <% @users.each do |user| -%>
    <tr>
      <td class="text-center"><% if user.is_admin %><span class='glyphicon glyphicon-star'><% end %>
      <td><%= user.login %></td>
      <td><%= user.email %></td>
      <td><%= user.description %></td>
      <td><button type="button" class='btn btn-xs btn-primary has-tooltip' title='Update user settings' data-toggle='modal' data-target="#user-<%= user.id %>-modal"><span class='glyphicon glyphicon-wrench'></span></button>  <%#= link_to "Permissions", edit_user_permissions_path(user) %> <%= link_to admin_user_path(user), method: :delete, data: { confirm: "You'e about to delete the user #{user.login}. Are you sure?" }, class: 'btn btn-xs btn-danger has-tooltip', title:'Delete user', 'data-toggle' => 'tooltip' do %><span class='glyphicon glyphicon-trash'></span><% end %></td>
    </tr>
  <% end -%>
</table>

eztsm/app/views/admin/users/user_modals_response.js.erb
<% if @user.errors.count > 0 %>
  $('#errors-<%= @user.id %>').html('<%= escape_javascript(render("shared/error_messages", :formats => [:html])) %>')
<% else %>
    window.location.href='<%= admin_users_path %>'
<% end %>